task5/megacrud/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete')
]

task5/task5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("megacrud.urls", namespace='user'))
]

task5/megacrud/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    username = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return f"account username is {self.username}"

task5/megacrud/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms

from .models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput())
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserUpdateForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput())
    email = forms.CharField(widget=forms.EmailInput(), required=False)

    class Meta:
        model = User
        fields = ('username', 'email')

task5/megacrud/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from .models import User
from .forms import UserLoginForm, UserRegisterForm, UserUpdateForm

# Create your views here.


def index(request):
    return render(request, 'index.html')


def login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = UserLoginForm()
    context = {
        "form": form
    }
    return render(request, 'login.html', context)


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('user:login'))
    else:
        form = UserRegisterForm()
    context = {
        'form': form
    }
    return render(request, 'register.html', context)


@login_required
def profile(request):
    return render(request, 'profile.html', {'user': request.user})


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('user:index'))


@login_required
def update(request):
    if request.method == "POST":
        # Инициализируем форму с данными из POST-запроса
        form = UserUpdateForm(data=request.POST, instance=request.user)
        if form.is_valid():
            # Сохраняем изменения пользователя (только first_name и last_name)
            form.save()
            return HttpResponseRedirect(reverse('user:profile'))  # Перенаправление на страницу профиля
    else:
        # Если GET-запрос, отображаем форму с текущими данными пользователя
        form = UserUpdateForm(instance=request.user)

    context = {
        'form': form
    }
    return render(request, 'update.html', context)

@login_required
def delete(request):
    user = request.user
    user.delete()
    return HttpResponseRedirect(reverse('user:index'))

task5/megacrud/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Главная страница</title>
</head>
<body>
    <button><a href="{% url 'user:login' %}">Войти</a></button>
</body>
</html>

task5/megacrud/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Логин</title>
</head>
<body>
   <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Войти</button>
        <button><a href="{% url 'user:register' %}">Нет аккаунта? Регистрируйтесь</a></button>
    </form>
</body>
</html>

task5/megacrud/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Профиль</title>
</head>
<body>
    <h1>Ваш ник: {{ user.username }}</h1>
    <h1>Ваш email: {{ user.email }}</h1>
    <button><a href="{% url 'user:update' %}">Редактировать</a></button>
    <button><a href="{% url 'user:logout' %}">Выйти</a></button>
</body>
</html>

task5/megacrud/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
<h2>Register</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Зарегистрироваться</button>
    </form>
</body>
</html>

task5/megacrud/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Редактирование профиля</title>
</head>
<body>
<h1>Отредактировать</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Изменить</button>
        <button><a href="{% url 'user:delete' %}">Удалить</a></button>
        <button><a href="{% url 'user:profile' %}">Назад</a></button>
    </form>
</body>
</html>